name: Test

on: 
  workflow_call:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3  
      
    - name: setup JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    # The starter workflow will run the build task by default.
    # In the default Gradle configuration, this command will download dependencies,
    #     build classes, run tests, and package classes into their distributable format, for example, a JAR file.
    # src : https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle#packaging-workflow-data-as-artifacts
    #
    # So this is enough for testing the project
    - name: Build with Gradle
      run: ./gradlew build --stacktrace

    - run: echo "Build status report=${{ job.status }}."
